# Generated by Django 4.2.7 on 2025-06-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0009_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_Carrossel1',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem_Carrossel2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem_Carrossel3',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='video',
        ),
        migrations.AddField(
            model_name='produto',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.empresa'),
        ),
    ]
